kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4

nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 30777
        hostPort: 30777
        protocol: TCP
      - containerPort: 30776
        hostPort: 30776
        protocol: TCP
  - role: worker
  - role: worker
  - role: worker
